#!/usr/bin/env node
// Draft YouTube copy: a channel blurb plus one ready-to-paste description per
// video, each carrying the app's detail page and a store link tagged
// ct=youtube so channel-driven installs show up separately in App Store
// Connect. Output lands in .tmp/ (git-ignored) — it is copy to paste into
// YouTube Studio, not something the site serves.

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const DOMAIN = 'https://apps.h53d.xyz';
const portfolio = JSON.parse(fs.readFileSync(path.join(ROOT, 'assets', 'apps.json'), 'utf8'));
const channel = JSON.parse(fs.readFileSync(path.join(ROOT, 'assets', 'youtube-channel.json'), 'utf8'));

const bySlug = new Map(portfolio.apps.map((a) => [a.slug, a]));

function storeLink(app) {
  const ios = (app.links && app.links.ios) || '';
  const pt = (ios.match(/[?&]pt=(\d+)/) || [])[1];
  const params = ['ct=youtube', 'mt=8'];
  if (pt) params.unshift(`pt=${pt}`);
  return `https://apps.apple.com/app/id${app.id}?${params.join('&')}`;
}

function firstSentence(text) {
  return String(text || '').split(/(?<=\.)\s/)[0].trim();
}

// The keyword blobs already stored per video make decent hashtags.
function hashtags(video, app) {
  const words = String(video.description || '')
    .replace(/[^\w\s+.-]/g, ' ')
    .split(/\s+/)
    .map((w) => w.replace(/^[.+-]+|[.+-]+$/g, ''))
    .filter((w) => w.length > 2 && !/^\d+$/.test(w));
  const fromApp = [app.name.replace(/[^A-Za-z0-9]/g, ''), 'iPhone', 'iPad', 'Mac'];
  const seen = new Set();
  const tags = [];
  for (const w of [...words, ...fromApp]) {
    const tag = w.replace(/[^A-Za-z0-9]/g, '');
    const key = tag.toLowerCase();
    if (!tag || seen.has(key)) continue;
    seen.add(key);
    tags.push('#' + tag);
    if (tags.length === 6) break;
  }
  return tags.join(' ');
}

const lines = [];
lines.push('# YouTube copy — paste into Studio');
lines.push('');
lines.push('Generated by `node scripts/youtube-copy.js`.');
lines.push('');
lines.push('YouTube strips clickability from links in Shorts descriptions (41 of these 57');
lines.push('videos are Shorts), so video copy uses plain-text domains: still readable by');
lines.push('viewers and by the crawlers and AI systems that summarise the channel.');
lines.push('Full tracked links (`ct=youtube`) stay in the two places that accept them —');
lines.push('the channel About links and playlist descriptions.');
lines.push('');

// ---------------------------------------------------------------- channel
lines.push('## 1. Channel description (About)');
lines.push('');
lines.push('```text');
lines.push('Native Apple apps for CAD, 3D and on-device AI — built by Wei Ai (Shanghai Foowei Information Technology).');
lines.push('');
lines.push('Open and review STEP, IGES, JT and DXF files on iPhone, iPad, Mac and Apple Vision Pro. Check and repair meshes for 3D printing, convert between CAD and mesh formats, and clean up images with local AI. Every app processes files on device: no accounts, no ads, no uploads.');
lines.push('');
lines.push('The videos here are short, practical demos: measurement and PMI, cross sections, exploded views, format conversion, and print checks.');
lines.push('');
lines.push('All apps, with privacy policies and support pages: ' + DOMAIN + '/');
lines.push('```');
lines.push('');
lines.push('## 2. Channel keywords (Studio → Settings → Channel → Basic info)');
lines.push('');
lines.push('```text');
lines.push('STEP viewer, IGES viewer, JT viewer, DXF viewer, CAD viewer iPhone, CAD viewer iPad, CAD viewer Mac, Apple Vision Pro CAD, STL to STEP, 3D model converter, 3D printing check, PMI GD&T, on-device AI, privacy first apps');
lines.push('```');
lines.push('');

// ---------------------------------------------------------------- playlists
lines.push('## 3. Suggested playlists');
lines.push('');
const counts = new Map();
for (const v of channel.videos) counts.set(v.slug, (counts.get(v.slug) || 0) + 1);
const ranked = [...counts.entries()]
  .filter(([slug, n]) => slug && bySlug.has(slug) && n >= 2)
  .sort((a, b) => b[1] - a[1]);
for (const [slug, n] of ranked) {
  const app = bySlug.get(slug);
  lines.push(`- **${app.name}** (${n} videos) — "${app.name}: ${app.promotional || 'demos'}" → link the playlist to ${DOMAIN}/apps/${slug}/detail.html`);
}
lines.push('');

// ---------------------------------------------------------------- videos
lines.push('## 4. Video descriptions');
lines.push('');
const orphans = [];
const grouped = new Map();
for (const v of channel.videos) {
  if (!v.slug || !bySlug.has(v.slug)) { orphans.push(v); continue; }
  if (!grouped.has(v.slug)) grouped.set(v.slug, []);
  grouped.get(v.slug).push(v);
}

for (const [slug, videos] of grouped) {
  const app = bySlug.get(slug);
  lines.push(`### ${app.name} (${videos.length})`);
  lines.push('');
  for (const v of videos) {
    lines.push(`**${v.title}**  `);
    lines.push(`<https://www.youtube.com/watch?v=${v.id}>`);
    lines.push('');
    lines.push('```text');
    lines.push(v.title.replace(/\s*#\S+/g, '').trim());
    lines.push('');
    lines.push(`${app.name} — ${app.promotional || firstSentence(app.desc)}`);
    lines.push(firstSentence(app.desc));
    lines.push('');
    lines.push(`Search "${app.name}" on the App Store, or open apps.h53d.xyz/apps/${slug}`);
    lines.push('');
    lines.push('Runs on device — no accounts, no ads, no file uploads.');
    lines.push('');
    lines.push(hashtags(v, app));
    lines.push('```');
    lines.push('');
  }
}

lines.push('## 5. Playlist descriptions (links work here)');
lines.push('');
for (const [slug, videos] of grouped) {
  const app = bySlug.get(slug);
  lines.push(`**${app.name}** (${videos.length} videos)`);
  lines.push('');
  lines.push('```text');
  lines.push(`${app.name} — ${app.promotional || firstSentence(app.desc)}`);
  lines.push(firstSentence(app.desc));
  lines.push('');
  lines.push(`App Store: ${storeLink(app)}`);
  lines.push(`Details, privacy policy and support: ${DOMAIN}/apps/${slug}/detail.html`);
  lines.push('```');
  lines.push('');
}

if (orphans.length) {
  lines.push('## 6. Videos not linked to an app');
  lines.push('');
  lines.push('These carry no slug in `assets/youtube-channel.json`, so they never appear on a detail page:');
  lines.push('');
  for (const v of orphans) {
    lines.push(`- ${v.title} — <https://www.youtube.com/watch?v=${v.id}>`);
  }
  lines.push('');
}

const outDir = path.join(ROOT, '.tmp');
fs.mkdirSync(outDir, { recursive: true });
const out = path.join(outDir, 'youtube-copy.md');
fs.writeFileSync(out, lines.join('\n'));
console.log(`wrote ${out} (${channel.videos.length} videos, ${grouped.size} apps, ${orphans.length} unlinked)`);
